## defaults for _all_ profiles
[default]
src = 'src'
# test = './src/test'
out = 'out'
libs = ['lib']
libraries = []
remappings = [
    'forge-std/=lib/forge-std/src/',
    'ds-test/=lib/ds-test/src/',
    '@openzeppelin/=lib/openzeppelin-conctracts/contracts',
]
cache = true
force = false
evm_version = 'london'
## Sets the concrete solc version to use, this overrides the `auto_detect_solc` value
solc_version = '0.8.12'
auto_detect_solc = true
optimizer = true
optimizer_runs = 200000
verbosity = 0
ignored_error_codes = []
fuzz_runs = 256
ffi = false
sender = '0x0000000000000000000000000000000000000529'
tx_origin = '0x0000000000000000000000000000000000000529'
initial_balance = '0xffffffffffffffffffffffff'
block_number = 0
chain_id = 1
gas_limit = 9223372036854775807
gas_price = 0
block_base_fee_per_gas = 0
block_coinbase = '0x0000000000000000000000000000000000000000'
block_timestamp = 0
block_difficulty = 0

# See more config options https://github.com/gakonst/foundry/tree/master/config
# 0x0000000000000000000000000000000000000529
# 0x00a329c0648769a73afac7f9381e08fb43dbea72
