version: 2.1


executors:
  smart_contracts:
    docker:
      - image: circleci/node:10.16.0
      - image: trufflesuite/ganache-cli
        command: ganache-cli -a 10


commands:
  install_node_modules:
    parameters:
      executor:
        type: string
    steps:
      - restore_cache:
          name: Restore yarn cache
          key: << parameters.executor >>-yarn-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          name: Save yarn cache
          key: << parameters.executor >>-yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.config/yarn

jobs:
  build_contracts:
    executor: smart_contracts
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - install_node_modules:
          executor: contracts
      - run:
          name: Compile
          command: yarn compile
      - run:
          name: Run tests with coverage
          command: yarn coverage
      - run:
          name: Upload coverage report to coveralls
          command: cat ./coverage/lcov.info | yarn coveralls

workflows:
  version: 2
  ci:
    jobs:
      - build_contracts:
          filters:
            branches:
              only:
                - master
